### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by Saiv46** [hufrea/byedpi#1]
Test command: `/opt/ciadpi --ip ::1 --method fake --ttl 1`

## General
- [X] Listens at `::1`
- [X] AAAA resolution
- [X] Mapped IPv4

### Default (SOCKS5, dual-stack)
- [X] V6-supported website
- [X] V6-only website

### Forced (SOCKS5, v6-only)
- [X] V6-supported website
- [X] V6-only website

### Bodge (SOCKS4, dual-stack)
- [ ] V6-supported website - ~~failover to v4~~ -> **fail**
- [ ] V6-only website - **not supported**

### My setup (SOCKS4, v6-only)
- [X] V6-supported website
- [ ] V6-only website - **not supported**

**Comment by hufrea** [comment]
`V6-supported website - fail`
It means that when requesting with a domain in the address, proxy uses IPv4?

**Comment by Saiv46** [comment]
> `V6-supported website - fail` It means that when requesting with a domain in the address, proxy uses IPv4?

Nope, it just doesn't open at all. Firefox also doesn't try to fallback to IPv4.

**Comment by hufrea** [comment]
Please check if the bug is fixed in the new release

**Comment by Saiv46** [comment]
Okay, looks like SOCKS4 is completely broken, not working even for IPv4. But SOCKS5 works flawlessly now, closing
