### ISSUE TITLE
Crash with --fake on Windows

### ISSUE THREAD

**Issue by EvgenKo423** [hufrea/byedpi#101]
**Environment:** Windows 7 SP1. ByeDPI v0.12+ at least.
**Reproduce Steps:**
Run proxy with any `--fake` value.

**Expected Result:** It works.
**Actual Result:** C0000005 Access violation @ [WriteFile](https://github.com/hufrea/byedpi/blob/v0.13/desync.c#L309).
```
C:\Program Files\ByeDPI>ciadpi.exe --ip 127.0.0.1 --fake -1 --debug 2
new event: fd: 220, evt: EV_ACCEPT, mod_iter: 0
accept: fd=224
new event: fd: 224, evt: EV_REQUEST, mod_iter: 1
new conn: fd=228, addr=178.248.237.68:443
new event: fd: 228, evt: EV_CONNECT, mod_iter: 2
new event: fd: 224, evt: EV_DESYNC, mod_iter: 1
desync params index: 0
host: habr.com (106)
temp file: C:\Users\}!{enR\AppData\Local\Temp\tE177.tmp

C:\Program Files\ByeDPI>ciadpi.exe --ip 127.0.0.1 --fake 1 --debug 2
new event: fd: 220, evt: EV_ACCEPT, mod_iter: 0
accept: fd=224
new event: fd: 224, evt: EV_REQUEST, mod_iter: 1
new conn: fd=228, addr=52.159.49.199:443
new event: fd: 220, evt: EV_ACCEPT, mod_iter: 0
accept: fd=244
new event: fd: 244, evt: EV_REQUEST, mod_iter: 3
new conn: fd=248, addr=184.51.252.165:80
new event: fd: 248, evt: EV_CONNECT, mod_iter: 4
new event: fd: 244, evt: EV_DESYNC, mod_iter: 3
desync params index: 0
host: www.msftconnecttest.com (53)
temp file: C:\Users\}!{enR\AppData\Local\Temp\t1392.tmp
```

**Comment by hufrea** [comment]
Для отправки используется TransmitFile, а он поддерживается с Windows 8.1, т.е. на 7-ке фейк не поддерживается. Упомяну об этом в README.

**Comment by EvgenKo423** [comment]
[Microsoft с вами не согласен](https://learn.microsoft.com/en-us/windows/win32/api/mswsock/nf-mswsock-transmitfile):
* в **Requirements**:
  > **Minimum supported client**	Windows 8.1, **Windows Vista** [desktop apps | UWP apps]
* в **Remarks**:
  > This function is supported **for Windows Store apps on Windows 8.1**

При этом там почему-то даже упоминаются XP, 2000 и NT 3.51!

Ошибка возникает ещё до вызова TransmitFile, при вызове WriteFile, при попытке записать значение по NULL-pointer'у.

---

Ещё один момент: вы вызываете функцию TransmitFile статично, а в **Remarks** сказано следующее:

> **Note** The function pointer for the **TransmitFile** function must be obtained at run time by making a call to the [**WSAIoctl**](https://learn.microsoft.com/en-us/windows/desktop/api/winsock2/nf-winsock2-wsaioctl) function with the **SIO_GET_EXTENSION_FUNCTION_POINTER** opcode specified. The input buffer passed to the **WSAIoctl** function must contain **WSAID_TRANSMITFILE**, a globally unique identifier (GUID) whose value identifies the **TransmitFile** extension function. On success, the output returned by the **WSAIoctl** function contains a pointer to the **TransmitFile** function. The **WSAID_TRANSMITFILE** GUID is defined in the _Mswsock.h_ header file.

Правда не ясно, так надо делать всегда или только когда нужен указатель...

**Comment by hufrea** [comment]
Точно! Виноват WriteFile, упустил эту строчку:
> Windows 7: Этот параметр не может иметь значение NULL.

> Minimum supported client Windows 8.1, Windows Vista [desktop apps | UWP apps]

Тут, наверное, наоборот должно быть? Windows 8.1 для UWP и XP для desktop apps. Или как это трактовать?

**Comment by EvgenKo423** [comment]
Наверно, тут как-то криво, да...

**Comment by EvgenKo423** [comment]
Спасибо, `--fake` работает.
