### ISSUE TITLE
Support "VPN mode"

### ISSUE THREAD

**Issue by yue374** [hufrea/byedpi#11]
I hope you can support VPN mode. Example: WinDivert. Because I need use proxy for another purpose.

**Comment by hufrea** [comment]
You can use [tun2socks](https://github.com/xjasonlyu/tun2socks). (will also need to look into [this](https://github.com/xjasonlyu/tun2socks/issues/32)).
There are other projects using WinDiwert: [GoodbeyDPI](https://github.com/ValdikSS/GoodbyeDPI) and [zapret](https://github.com/bol-van/zapret).

**Comment by yue374** [comment]
Thank you for suggestion!
