### ISSUE TITLE
Error using fake. Android.

### ISSUE THREAD

**Issue by Stepman123** [hufrea/byedpi#113]
Пробовал сначала apk сборки из другого репозитория и с ними не работало.
При включенном fake трафик вообще не идет.
В последней версии из этого репозитория, 0.13.1 arm7, тоже самое. Ошибка видна в терминале.
Андроид 7.1.2; p7500; arm7

![1725137982240](https://github.com/user-attachments/assets/1a245d74-8285-4cbc-9ef6-1850fa2b71a8)

**Comment by Stepman123** [comment]
Это в сммом деле исправлено?
Я бы проверил если что.

**Comment by hufrea** [comment]
> Это в самом деле исправлено?

Ошибка из скриншота да, но, судя по всему, с фейками есть другие проблемы на Android с ядром версии ниже 4.17.

> Я бы проверил если что.

Можете сделать это в [Termux](https://github.com/termux/termux-app/releases):
```sh
pkg install make clang git
git clone https://github.com/hufrea/byedpi.git
cd byedpi
git checkout 950e85d
make
./ciadpi -x 1 -f -1
```

**Comment by Stepman123** [comment]
>

Тут устаревший CPU arm 7 без NEON. Так что почти ничего не поддерживается в термукс.
Но я пробовал PowerTunnel с плагином LibertyTunnel, у него есть fake который работает. Например, разблокировал TLS 1.2 сайт rezka.ag. Хотя, прога малополезная по разным причинам и fake там не такой, нет отдельного пакета с маленьким ttl, а просто заменяется SNI на что-нибудь стороннее и так работает. Используется технология типа https MITM proxy. Многие сайты отказывают.

**Comment by Stepman123** [comment]
В 14.1 другая ошибка

![1726909086592](https://github.com/user-attachments/assets/1fb25216-5bc2-4dee-a05b-e2e398897962)
