### ISSUE TITLE
Possible Undefined behavior in ANTOHS macros

### ISSUE THREAD

**Issue by dartvader316** [hufrea/byedpi#117]
When i used compiled binary on main branch with clang sanitizers i got this:
```
packets.c:94:25: runtime error: left shift of negative value -1
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior packets.c:94:25
```
The error shows that the problem is possibly in `ANTOHS` macos in `packets.c` .
Unfortunately i don't know how to reproduce this because i did not enable debug output when got this, however i think it's better to fix this possibility of UB by adding check for negative values in this code.

**Comment by hufrea** [comment]
After the fix, the value is cast to unsigned type, so i think the problem is solved.
