### ISSUE TITLE
Не запускается на архитектуре mips

### ISSUE THREAD

**Issue by hachikoharuno** [hufrea/byedpi#14]
Хотел запустить на роутере с процессором MediaTek MT7621, но появляется ошибка:
`line 3: syntax error: unexpected "("
` 
Скрипты запрета определили бинарники для него как mips32r1-lsb

**Comment by hufrea** [comment]
А как вы запускали?

**Comment by hachikoharuno** [comment]
Установлена OpenWrt. Через scp перекинул по ssh фаил на роутер и запустил командой. Данную ошибку выдет как без параметров так и с ними

**Comment by hufrea** [comment]
Попробуйте установить ipk файл отсюда: https://github.com/spvkgn/ByeDPI-OpenWrt/releases

**Comment by hachikoharuno** [comment]
Спасибо, что быстро отреагировали. Все заработало.
Архитектура оказалась конкретно: mipsel_24kc для MT7621 (видимо в этом была проблема)
Настроил все через Tinyproxy, работает нормально.

Напишу сюда конфигурацию, если вдруг кому будет интересно:
```
config tinyproxy
        option enabled '1'
        option User 'nobody'
        option Group 'nogroup'
        option Port '2020'
        option Timeout '600'
        option DefaultErrorFile '/usr/share/tinyproxy/default.html'
        option StatFile '/usr/share/tinyproxy/stats.html'
        option LogFile '/var/log/tinyproxy.log'
        option LogLevel 'Info'
        option MaxClients '100'
        option MinSpareServers '5'
        option MaxSpareServers '20'
        option StartServers '10'
        option MaxRequestsPerChild '0'
        option ViaProxyName 'tinyproxy'
        option Bind '0.0.0.0'

config upstream
        option type 'proxy'
        option via 'socks5 0.0.0.0:1080'
upstream socks5 user:pass@domain.com:port
```

**Comment by Miraihi** [comment]
Через entware та же самая ошибка. `./ciadpi: line 3: syntax error: unexpected "("`. Tinyproxy не обойдусь.

**Comment by hufrea** [comment]
> Запускал просто бинарник из папки

Какой? Из OpenWrt репозитория или отсюда?

**Comment by Miraihi** [comment]
Отсюда [byedpi-11.2-mips](https://github.com/hufrea/byedpi/releases/download/v0.11.2/byedpi-11.2-mips.tar.gz)

**Comment by redarrow-rus** [comment]
> Спасибо, что быстро отреагировали. Все заработало. Архитектура оказалась конкретно: mipsel_24kc для MT7621 (видимо в этом была проблема) Настроил все через Tinyproxy, работает нормально.
> 
> Напишу сюда конфигурацию, если вдруг кому будет интересно:

Как получилось настроить? byedpi ни в какую не принимает запросы с роутера. Просто глухое молчание. Притом что запросы с обычных машин (linux) обслуживаются нормально.

**Comment by hachikoharuno** [comment]
Хочу также отметить, что в данном сценарии tinyproxy совсем не нужен, для меня был не понятен принцип работы и я сделал через него по незнанию, в действительности byedpi сам поднимает прокси сервер, только socks, а не http и если прописать socks в настройки прокси или наоборот на клиенте, то работать не будет.

**Comment by redarrow-rus** [comment]
Да, спасибо, разобрался!

**Comment by 0x131313** [comment]
@hachikoharuno @redarrow-rus 
подскажите пожалуйста, а как вы в итоге настроили прокси на роутере для byedpi без tinyproxy?

**Comment by hachikoharuno** [comment]
> @hachikoharuno @redarrow-rus подскажите пожалуйста, а как вы в итоге настроили прокси на роутере для byedpi без tinyproxy?

Он работает как обычный прокси сервер, поэтому достаточно просто его запустить с конифгом и после этого прописать адрес роутера + порт byedpi в настройках браузера или системы. Чтобы он стартовал при каждом запуске роутера можно просто добавить команду в sh скрипт и закинуть его в автозагрузку(ну или написать для него сервис).

Если вас интересует именно режим transparent proxy, то тут не подскажу. Iptables у меня не работают, а под nft нет нормальных инструкций.

**Comment by redarrow-rus** [comment]
Всё так, да. byedpi сам по себе работает как прокси, на него надо направлять трафик, а дальше он сам...

Хороший мануаль (хоть и непростой), как со всем этим хозяйством совладать на роутере: https://habr.com/ru/articles/767458/. При этом в статье описан внешний прокси, но вместо него можно как раз byedpi использовать.
