### ISSUE TITLE
`--auto=torst` doesn't terminate a group / Connection closed

### ISSUE THREAD

**Issue by EvgenKo423** [hufrea/byedpi#144]
**Environment:** Windows 7 SP1. ByeDPI v0.13.1+ at least.
**Reproduce Steps:**
1. Run proxy with `ciadpi.exe -i 127.0.0.1 -H :example.com -s 4 -A t -T 1 -s 4`;
2. Open any website except `example.com`.

**Expected Result:** It works.
**Actual Result:** Proxy closes the connection.
```
new event: fd: 220, evt: EV_ACCEPT, mod_iter: 0
accept: fd=224
new event: fd: 224, evt: EV_REQUEST, mod_iter: 1
new conn: fd=228, addr=34.240.60.66:443
new event: fd: 228, evt: EV_CONNECT, mod_iter: 2
new event: fd: 224, evt: EV_DESYNC, mod_iter: 1
close: fds=224,228, recv: 517,0, rounds: 1,0
new event: fd: 220, evt: EV_ACCEPT, mod_iter: 0
accept: fd=228
new event: fd: 228, evt: EV_REQUEST, mod_iter: 5
new conn: fd=224, addr=34.240.60.66:443
new event: fd: 224, evt: EV_CONNECT, mod_iter: 6
new event: fd: 228, evt: EV_DESYNC, mod_iter: 5
close: fds=228,224, recv: 517,0, rounds: 1,0
...
```

**Workaround:** Add `-A n` before `-A t`.

The `-A t` itself should close the first group, isn't it?

**Comment by hufrea** [comment]
The first group is limited by hosts, the second by trigger (torst works for the first group), the third does not exist, there is no suitable group. You need to add `-A n`, that's how it should be.

**Comment by hufrea** [comment]
Yes, I'll fix it. But implicit groups cannot be relied upon; they are not described anywhere and may well be removed in other versions.
