### ISSUE TITLE
Новый вариант byedpi.service ломает работоспособность

### ISSUE THREAD

**Issue by GambitVKM** [hufrea/byedpi#149]
[https://github.com/hufrea/byedpi/blob/main/dist/linux/byedpi.service](https://github.com/hufrea/byedpi/blob/main/dist/linux/byedpi.service)
`ExecStart=/usr/bin/ciadpi --split 1 --disorder 3+s --mod-http=h,d --auto=torst --tlsrec 1+s $ARGS`
На мой взгляд опции корректнее поместить в конфиг. Это лучше, чем размазывать ключи тонким слоем по разным файлам.
К тому же у меня, например, второй аргумент ломает работоспособность.

**Comment by lufog** [comment]
Переопредели сервис и добавь в него:
```service
[Service]
// ...
EnvironmentFile=-/etc/byedpi
ExecStart=ciadpi $OPTIONS
```

в etc создай файл byedpi, со следующим содержимым:
```
OPTIONS="--disorder 1"
```

Из плюсов не нужно делать `daemon-reload` после правки ключей, как при редактировании `.service` файла напрямую.

**Comment by GambitVKM** [comment]
Это понятно. Вопрос в том зачем вообще пихать ключи в файл сервиса?
Есть конфиг. Может, все же стоит хранить _все_ параметры конфигурации именно там?
Нужно передать некие дефолтные значения? Так внести их туда сразу.

**Comment by andrewclarkii** [comment]
> @GambitVKM, отредактируй (ну или переопредели) сервис и добавь в него:
> 
> ```desktop
> [Service]
> // ...
> EnvironmentFile=-/etc/byedpi
> ExecStart=ciadpi $OPTIONS
> ```
> 
> в `/etc/` создай файл `byedpi`, со следующим содержимым (со своими ключами, разумеется):
> 
> ```dotenv
> OPTIONS="--disorder 1"
> ```
> 
> Из плюсов, не нужно делать `daemon-reload` после правки ключей, как при редактировании `.service` файла 
> напрямую.
У меня byedpi не хотел настройки окружения читать, либо я что-то неверно сделал
 
> Себе для Arch Linux накидал [PKGBUILD](https://github.com/lufog/byedpi-bin), хранит "настройки" в `/etc/` и ставится системным, а не пользовательским сервисом.

https://github.com/hufrea/byedpi/pull/134
Собрал rpm, сейчас разбираюсь как deb собирать. Автор, почему-то, мержить не спешит.

**Comment by GambitVKM** [comment]
@lufog, с переопределением сервиса понятно. На данный момент у меня так и сделано.
Вопрос в том, зачем вообще ключи в файле сервиса? В AUR [задаются тем же вопросом](https://aur.archlinux.org/packages/byedpi#comment-991387).
Есть конфиг. Может, все же стоит хранить все параметры конфигурации именно там?
Нужно передать некие дефолтные значения? Так внести их туда сразу.

**Comment by hufrea** [comment]
> На мой взгляд опции корректнее поместить в конфиг.

Да, так будет правильнее, можно использовать EnvironmentFile, как предлагает @lufog. Раз уже есть готовые юниты, возможно кто-то пришлет PR, а нет, так сам поправлю позже.

>  Собрал rpm, сейчас разбираюсь как deb собирать. Автор, почему-то, мержить не спешит.

Мне же это поддерживать потом придется, необходимо все протестировать, изучить (вдруг в PR что-то сделано некорректно). А то выйдет как тут, с systemd.

**Comment by andrewclarkii** [comment]
> Да, так будет правильнее, можно использовать EnvironmentFile, как предлагает @lufog. Раз уже есть готовые юниты, возможно кто-то пришлет PR, а нет, так сам поправлю позже.

Вы имеющееся сначала возмите. В моем .service файле, который я проверял, так и было сделано. Я его не приложил, правда. Так же я исправил makefile на предмет определения опций компиляторов по-умолчанию в разных дистрибутивах.
 
> > Собрал rpm, сейчас разбираюсь как deb собирать. Автор, почему-то, мержить не спешит.
> 
> Мне же это поддерживать потом придется, необходимо все протестировать, изучить (вдруг в PR что-то сделано некорректно). А то выйдет как тут, с systemd.
Так сделано так, что бы имеющееся собиралось в пакет сразу же. Я тут появляюсь переодически, смогу помогать по мере возможности.

**Comment by trevarj** [comment]
> Вопрос в том, зачем вообще ключи в файле сервиса?

Потому что, я ленивый!

**Comment by radioxoma** [comment]
А почему такой суровый конфиг по-умолчанию? И его нет в примерах в README. Всё, что серьёънее  `--split` может ломать сайты, с `--disorder` на неделе были приключения.

**Comment by hufrea** [comment]
> а почему такой суровый конфиг по-умолчанию?

Обычный `--split` не работает на многих провайдерах, т.к. они уже давно научились пересобирать запрос (хотя на YouTube он все еще может действовать).
`--disorder` до ютубовских блокировок работал хорошо и практически ничего не ломал (кроме HTTP у некоторых).
Этот конфиг взят из батника для Windows, где `--disorder` работает некорректно из-за полной ретрансмиссии  и упомянут [тут](https://github.com/hufrea/byedpi/blob/f11f5b0d676c3c7ab3e4710db60bae675a0a0a2b/README.md?plain=1#L180).
После был немного изменен по предложению [отсюда](https://github.com/hufrea/byedpi/discussions/58#discussion-7031626).

**Comment by radioxoma** [comment]
Я имел в виду, что лучше пусть из-за дефолтного конфига не работает обход блокировок, чем ломается доступ ко всей сети.  Хотя... только что с ним ещё раз проверил, часть незаблокированных и заблокированных сайтов стала открываться..

**Comment by nebulosa2007** [comment]
Засинхронизировал файлы .conf и .service

Еще вроде полезная функция [Dynamic user feature](https://aur.archlinux.org/packages/byedpi#comment-987107), может  тоже добавите?

**Comment by lufog** [comment]
@nebulosa2007, она доступна только для системного сервиса, а этот хотят оставить универсальным (подробнее тут #152). Не запаривайся, просто скопируй файл в репу и добавь `DynamicUser`. Все равно ставишь сервис системным. Сам так же делаю.

**Comment by GambitVKM** [comment]
Мне кажется, вопрос решен в полном объеме и issue можно закрывать.
