### ISSUE TITLE
[Wishlist] Read options from config file

### ISSUE THREAD

**Issue by spvkgn** [hufrea/byedpi#15]
Если есть возможность, было бы здорово добавить опцию для чтения опций запуска из файла конфигурации.
Тогда на openwrt-роутере можно будет запускать как сервис и, возможно, будет смысл сделать конфигурирование через UCI.

**Comment by hufrea** [comment]
В проект придется тянуть дополнительную зависимость в виде парсера, а параметров не так уж много, чтобы в этом была необходимость. Аргументы можно прописать и в команду запуска. Или же назначить исполняемым файлом скрипт, в котором будут параметры.

**Comment by lufog** [comment]
Тоже пару раз посещала мысль, о пользе возможности чтения параметров из конфига. Например, для опакечивания (добавления  в AUR). Чтобы конфиг лежал себе в `/etc/byedpi.conf` и не слетал при обновлении пакета. Может можно конечно как-то, переопределить `.service` ну или обойти это хуками pacman'а, особо не вникал пока...
