### ISSUE TITLE
Unrecognized option '--disoob'

### ISSUE THREAD

**Issue by superclaw** [hufrea/byedpi#150]
Hi! Today my config have stopped to work: "--disorder 1 --oob 3+s --ttl 1 -A torst --tlsrec 1+s --debug 1"
I wanna try option "--disoob" instead of "--oob" but I'm getting an error "Unrecognized option '--disoob'".
Is that option available now, or I have to try some other?
Ubuntu server, last version of repo, Game-Service.

**Comment by hufrea** [comment]
> Is that option available now

Yes.
Check the version using `--version` and make sure it is 13+.

**Comment by superclaw** [comment]
> > Is that option available now
> 
> Yes. Check the version using `--version` and make sure it is 13+.

I'd checked and got "12". I'm just cloning this repo and "make", then "ciadpi". Should I use any other branch?

**Comment by superclaw** [comment]
UPD: I run it in docker container, maybe it uses cache. Is 13 version new?

**Comment by skiandrius** [comment]
> UPD: I run it in docker container, maybe it uses cache. Is 13 version new?

The latest version, v0.14.1, was released 5 days ago

**Comment by superclaw** [comment]
> > UPD: I run it in docker container, maybe it uses cache. Is 13 version new?
> 
> The latest version, v0.14.1, was released 5 days ago

It seems to be the cache inside of the docker container, thanks a lot, I'll try to fix
