### ISSUE TITLE
[GUI] concept

### ISSUE THREAD

**Issue by shikulja** [hufrea/byedpi#153]
Может кому пригодится, доделывать не собираюсь
исходник 40кб(с фаршем ну чуть больше)+воркфлов, не так уж много для проекта

![Снимок экрана 2024-09-23 175549](https://github.com/user-attachments/assets/f91d6997-f29c-44f4-b186-90795367bd36)
![Снимок экрана 2024-09-23 175515](https://github.com/user-attachments/assets/5b86aae9-d1e4-49d8-9912-6b5aa5bd11f7)

Что нужно доделать:
- Сгруппировать кнопки (я не еще не знаком с прогой, да и задумку авторов не знаю как лучше сделать группировку)
- Доработать обработку аргументов
- Рефакторинг можно сократить код в 2 раза, и добавить еще плюшек. (спагетти код не баг а фича)

По фану:
- Управление сервисами
- Модуль локализации
- Переключение тем
- Заполнить окно о программе ссылками (кстати вкладку потерял упс)
- подгружать блеклист ?
- еще что-нибудь забыл

Сборка кода
pip install pyinstaller
pyinstaller --onefile --windowed gui.py
+зависимости toml и PyQt6

src (бинарник не влез итоговый размер 34Mb может урезать зависимости?)
UPD1 [gui.zip](https://github.com/user-attachments/files/17101127/gui.zip) (поправил подсказки)

**Comment by git4rker** [comment]
а почему на питоне то?)
