### ISSUE TITLE
FreeBSD target binary?

### ISSUE THREAD

**Issue by zetcamp** [hufrea/byedpi#16]
Шутки про то, как пропатчить КДЕ под БСД уже были? Хотелось бы узнать у уважаемого автора - возможно ли собрать бинарь под FreeBSD, конкретно под актуальный Opnsense (FreeBSD 14.1)? В том смысле, будут ли релизы под FreeBSD?

Если нет, то хотя бы какую-то наводку для ламеров, как ловчее из исходников собрать рабочий вариант, если это возможно. Спасибо.

**Comment by hufrea** [comment]
Раз кому-то это нужно, то я постараюсь поддерживать и FreeBSD, но пока не могу сказать - будет ли текущая версия компилироваться и работать там.

**Comment by dbgerr** [comment]
самый ловчий способ - это закомментить -D_XOPEN_SOURCE=500 в Make-файле или заменить на -D_BSD_SOURCE  (_DEFAULT_SOURCE/_GNU_SOURCE - не рекомендуется :)) там на фрихе в каком-то хидере проверяется posix-совместимость. Ещё вариант закомментить во всех файлах #define _GNU_SOURCE, если где-то хидеров не хватает, то добавить. собирается clang17, gcc13 тоже должно. freebsd 13.2 продолжайте и дальше игнурить фрихую спосибо

**Comment by dbgerr** [comment]
также прилагается фантастически конпелирующаяся версия под бизда что-то рядом с v0.11.3, разумеется с несколькими ворнингами, а то там уже якобы нужные ОС (ну вы понели) подтягиваются на очередную часть всеми любимого Здрасте :) error.h не нуждается в представлении и подойдёт из любого акта, может быть
https://fastupload.io/fea493cb2afbac2b

**Comment by zetcamp** [comment]
@dbgerr, увы, глаза боятся, а руки - крюки. В общем, собрать под БСД простым make не получилось.
Вдаваться в подробности не буду, потому это всё дилетанство.
Error.h заменил на err.h, как пишут в этих ваших инторнетах. Но там ещё куча не связанных с ним ошибок про необъявленные переменные.
В такую глубину глубин я без акваланга программирования погружаться уже не готов. 

Подождём, может автор допилит, по возможности, под БСД. Ну а нет, так и ладно.

**Comment by redarrow-rus** [comment]
Дай бог вам здоровья, ребят, за эти патчи и обсуждение.

**Comment by zetcamp** [comment]
@redarrow-rus, завелось на фряхе? Я тоже собрал, спасибо крайним патчам. Но пока из-за скудности применяемых ключей (фейк и прочие - недоступны) - работает так себе.
Побороть тот же ютуп для всех клиентов локальной сети сразу (компы, телефоны, телевизоры) так и не получилось на вротцеликоме, будь он не ладен.

Если удалось хоть что-то, поделитесь рабочими конфигами ключей?

**Comment by redarrow-rus** [comment]
Завелось. Собралось без ошибок. И работает out of box.

Автору низкий поклон.

**Comment by zetcamp** [comment]
@redarrow-rus, а ключи какие используются?

**Comment by redarrow-rus** [comment]
Для пробы без ключей запускал. Порт по умолчанию 1080.

**Comment by redarrow-rus** [comment]
Поправка. Попробовал на другом провайдере - дефолтные настройки (без ключей) не сработали. Попытаюсь поэкспериментировать.
