### ISSUE TITLE
socket: Address family not supported by protocol (mipsle)

### ISSUE THREAD

**Issue by Baltazar500** [hufrea/byedpi#169]
Привет.

На стареньком плеере попробовал заюзать утилиту и обломался. socks5-запросы curl'a не проходят через byedpi в принципе (использовал только аргументы порта, хоста, да дебага) и валится ошибка
```
socket: Address family not supported by protocol
```

**Comment by hufrea** [comment]
Добавьте ещё опцию `--conn-ip 0.0.0.0`.

**Comment by Baltazar500** [comment]
@hufrea, спасибо помогло. На виртуальной машины с линуксом этой опции не требовалось. Почему вопрос и возник :/
