### ISSUE TITLE
Ошибка ss: invalid version: 0x43

### ISSUE THREAD

**Issue by artem-burashnikov** [hufrea/byedpi#18]
С любыми опциями на Linux получаю `ss: invalid version: 0x43`

**Comment by hufrea** [comment]
Я думаю вы прописали прокси как HTTP, а не SOCKS.

**Comment by artem-burashnikov** [comment]
> Я думаю вы прописали прокси как HTTP, а не SOCKS.

Вы правы. Спасибо.
