### ISSUE TITLE
By Magisk on Termux use byedpi

### ISSUE THREAD

**Issue by sevcator** [hufrea/byedpi#192]
Using Termux with SU I am tries to use byedpi, i built it and open in su

```
:/data/data/com.termux/files/home/byedpi # ./ciadpi -E -n “www.google.com” -q 1+s -O 1 -s 25+s -t 5
sni: “www.google.com”
```

I am tries many parameters but it still block sites and YouTube.

**Comment by hufrea** [comment]
Did you redirect the traffic to the proxy?

**Comment by sevcator** [comment]
I use the transparent proxy
