### ISSUE TITLE
add_event: pool is full

### ISSUE THREAD

**Issue by sevcator** [hufrea/byedpi#197]
When i try to open proxy and use byedpi tell me: 'add_event: pool is full'

Logs:
```
~ $ su
:/data/data/com.termux/files/home # cd byedpi
/ciadpi --port 1338                                      <
add_event: pool is full
add_event: pool is full
add_event: pool is full
add_event: pool is full
add_event: pool is full
recv: Connection reset by peer
add_event: pool is full
add_event: pool is full
add_event: pool is full
add_event: pool is full
recv: Connection reset by peer
add_event: pool is full
add_event: pool is full
```

Xiaomi Redmi 9C NFC, armv7, Android 10, Tunneled proxy by ProxyDroid with selected apps, byedpi executed via Termux.

**Comment by hufrea** [comment]
You need to exclude Termux from proxied applications.

**Comment by doroved** [comment]
> You need to exclude Termux from proxied applications.

will byedpi work on a linux virtual machine on macOS? I run it, but I get the same messages.
```
add_event: pool is full
add_event: pool is full
add_event: pool is full
```
I wanted to direct the proxy to a local Linux machine with the byedpi key in the wifi settings.
