### ISSUE TITLE
Windows: unknown option -- Y (drop-sack)

### ISSUE THREAD

**Issue by LisPavel** [hufrea/byedpi#199]
Скачал архив [14.1](https://github.com/hufrea/byedpi/releases/download/v0.14.1/byedpi-14.1-x86_64-w64.zip)
Пытаюсь запустить из папки `./ciadpi.exe -s1 -q1 -Y -At -f-1 -r1+s -As -Kuh -b665 -An` и `./ciadpi.exe -s1 -q1 --drop-sack -At -f-1 -r1+s -As -Kuh -b665 -An` 
Ругается на параметр -Y и --drop-sack
![image](https://github.com/user-attachments/assets/b29d7531-20ff-4779-9c10-3a06e95e9d89)

**Comment by lp85d** [comment]
Вот верная комбинация
https://github.com/hufrea/byedpi/releases/download/v0.15/byedpi-15-aarch64.tar.gz
Распаковали /data/data/com.termux/files/home/Downloads запустили
/data/data/com.termux/files/home/Desktop/ciadpi-aarch64 --ip 0.0.0.0 --port 1080 --tls-sni "www.youtube.com" -s1 -q1 -Y -At -f-1 -r1+s -As -Kuh -b665 -An
