### ISSUE TITLE
Использование без прокси

### ISSUE THREAD

**Issue by oifj34f34f** [hufrea/byedpi#2]
Можно ли использовать byedpi по всей системе, как это делают zapret/goodbyedpi, то есть без необходимости указывать прокси сервер в каждой программе?

**Comment by oifj34f34f** [comment]
Извиняюсь, затупил. Насколько я понял, можно просто в настройках системы указать прокси, и всё.

**Comment by EvgenyKV** [comment]
> Извиняюсь, затупил. Насколько я понял, можно же просто в настройках системы указать прокси

можно, но не все проги будут подхватывать, например:

"Указанные параметры прокси-сервера не будут использованы всеми приложениями. В частности, Firefox, приложения, основанные на Firefox, а также любые другие приложения, основанные на QtWebEngine, в том числе Konqueror, использующий модуль WebEnginePart, Akregator и Falkon не используют эти параметры. Некоторые приложения позволяют настраивать параметры прокси-сервера самостоятельно."
