### ISSUE TITLE
Не помогает с twitter

### ISSUE THREAD

**Issue by artem-burashnikov** [hufrea/byedpi#20]
Так и должно быть или надо искать корректные настройки?

**Comment by EvgenyKV** [comment]
> Так и должно быть или надо искать корректные настройки?

ciadpi -i 127.0.0.1 -p 10801 -d 1
и настроить DoH, например, так:
https://help.keenetic.com/hc/ru/articles/360007687159-%D0%9F%D1%80%D0%BE%D0%BA%D1%81%D0%B8-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D1%8B-DNS-over-TLS-%D0%B8-DNS-over-HTTPS-%D0%B4%D0%BB%D1%8F-%D1%88%D0%B8%D1%84%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-DNS-%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%BE%D0%B2

у меня так работают твитор, мордокнига и инста без всяких hosts

**Comment by tkzv** [comment]
> Facebook, twitter заблокированы также и по ip.
> 
> Поэтому в дополнение надо прописывать в hosts незаблокированные ip адреса.

Фейсбук работает, abs-0.twimg.com — нет. Куда копать?
