### ISSUE TITLE
Владелец программы украл данные карты
ОН ВЕРНУЛ ДЕНЬГИ

### ISSUE THREAD

**Issue by ggfhgrehytht** [hufrea/byedpi#207]
Владелец программы украл 500₽ с помощью программы

**Comment by lllyx1** [comment]
Как ты это понял?

**Comment by vehametra** [comment]
Правда? а как?

**Comment by davikch** [comment]
Капеееец
Кремлеботы даже на гитхабе есть (проверьте коммиты)

**Comment by Axa-Ru** [comment]
Фигасе. Автор красава. В приложении с открытым исходным кодом как то умудрился вставить код ворующий деньги.

**Comment by vehametra** [comment]
А есть отладочный лог с DPI  системы?

**Comment by Axa-Ru** [comment]
Нет у него ничего. У этого Кости и аккаунт пустой. Кремлебот.

**Comment by LeviPesin** [comment]
ну теперь у него есть 40 рублей

**Comment by ggfhgrehytht** [comment]
> Константин, идите ка уроки учить лучше !!!

иди нахуй

**Comment by ggfhgrehytht** [comment]
> А есть отладочный лог с DPI системы?

проебал

**Comment by ggfhgrehytht** [comment]
> Правда? а как?

хз

**Comment by lllyx1** [comment]
> > Кремлеботы
> 
> какой нахуй кремлебот

Осеннее обострение у человека, лечится иди

**Comment by ggfhgrehytht** [comment]
> > > Кремлеботы
> > 
> > 
> > какой нахуй кремлебот
> 
> Осеннее обострение у человека, лечится иди

твоя мать шлюха, завали ебало уебище ебанное
