### ISSUE TITLE
byedpi поверх docker 

### ISSUE THREAD

**Issue by Rem-u** [hufrea/byedpi#209]
Хотя бы инструкцию напиши как этим в linux пользоваться. Мне просто сервер socs5 воно и не нужно если через него невозможно пропустить трафик. Работает только с curl -proxy 127.0.0.1
Собственно никак не могу прокси поверх docker пустить, redsocs даже не помогает  iptables тоже, я там все подключения через ВПН пробросил кроме докера и всёравно не работает никак, вооюще. 
Либо я чегото не понимаю либо ты хотяб напиши инструкцию в readme как мне не отдельно, а хотя бы весь трафик машины пустить через byedpi
Даже chatgpt уже не знает что делать

А насчёт самого трафика, он так должен идти: телефон - сервер - ВПН сервер в docker - byedpi - сайт

**Comment by virxkane** [comment]
Add tinyproxy to this chain.

**Comment by Rem-u** [comment]
> Add tinyproxy to this chain.

to pass all traffic through byedpi, are you suggesting that I install another proxy server? Well, I put it on, it still doesn't work!

I need any traffic from the PC to go through byedpi. I've already spent 9+ hours setting it up, but nothing is working.  Can you just write a script so that byedpi starts working?

**Comment by virxkane** [comment]
> to pass all traffic through byedpi, are you suggesting that I install another proxy server? Well, I put it on, it still doesn't work!

It's needed only to convert http proxy request to socks5 proxy request.

You need add next line into `tinyproxy.conf`:
```
upstream socks5 127.0.0.1:1080
```
Then configure your software to use tinyproxy instead of byedpi. All trafic from tinyproxy will be redirected to byedpi.

**Comment by SailorMax** [comment]
> хотя бы весь трафик машины пустить через byedpi

Вот тут пример решения в докере и с фильтрацией чего именно пускать через byedpi: https://github.com/SailorMax/anti-dpi-proxy
