### ISSUE TITLE
TCL Failed to open VPN

### ISSUE THREAD

**Issue by Chih13** [hufrea/byedpi#210]
На телевизоре TCL ATV 11 при использовании любых параметров в командной строке, а так же при пустой ком. строке при попытке подключения пишет Failed to open VPN. Без использования ком. строки подключается, но ютуб не работает
![photo_2024-10-20_17-08-24](https://github.com/user-attachments/assets/97a49760-7005-4f7a-adff-d2b7a82f6f5f)

**Comment by i3ee1394** [comment]
Аналогичная проблема на TCL с 11 android.

**Comment by Viktor45** [comment]
Ваши сообщение и скриншоты не относятся к программе byedpi которая тут обсуждается, но на телевизорах TLC с похожими проблемами помогает обновления их прошивок на самые свежие, где андроид не так урезан.

**Comment by excorprus** [comment]
к конфигу добавить нужно -i 127.0.0.1 -p 1080
После этих строчек лечилка ютуба заработала

**Comment by Maksimka820** [comment]
> В byebyedpi к конфигу добавить нужно -i 127.0.0.1 -p 1080 После этих строчек лечилка ютуба заработала

Как изменять конфиг в байдипиай? У меня нет такой настройки

**Comment by excorprus** [comment]
> > В byebyedpi к конфигу добавить нужно -i 127.0.0.1 -p 1080 После этих строчек лечилка ютуба заработала
> 
> Как изменять конфиг в байдипиай? У меня нет такой настройки

в настройках заходи в редактор командной строки, там после подобранной стратегии и нужно добавлять код указанный выше.

пример:   -o1 -d1 -a1 -At,r,s -s1 -d1 -s5+s -s10+s -s15+s -s20+s -r1+s -S -a1 -As -s1 -d1 -s5+s -s10+s -s15+s -s20+s -S -a1 -i 127.0.0.1 -p 1080
