### ISSUE TITLE
Контейнер для Mikrotik

### ISSUE THREAD

**Issue by lordot** [hufrea/byedpi#27]
Есть готовый микротик, на котором хочу поднять ваш докер контейнер, но проблема в том, что образ у вас собран для amd64 архитектуры. Нигде не нашел исходный Dockerfile. Не могли бы вы собрать образ для arm?

**Comment by hufrea** [comment]
Но я не делал никаких контейнеров (да и не планировал). Вам нужно обращаться не сюда, а к автору контейнера.

**Comment by Direnor** [comment]
> Есть готовый микротик, на котором хочу поднять ваш докер контейнер, но проблема в том, что образ у вас собран для amd64 архитектуры. Нигде не нашел исходный Dockerfile. Не могли бы вы собрать образ для arm?

Подскеажите, Вам удалось найти контейнер для микротика ? Если да, то киньте пожалуйста ссылку.

**Comment by 1ns0mn1a-god** [comment]
> Подскеажите, Вам удалось найти контейнер для микротика ? Если да, то киньте пожалуйста ссылку.

Дак текущий проект есть  https://hub.docker.com/r/tazihad/byedpi
Всё отлично работает.

**Comment by lordot** [comment]
> > Подскеажите, Вам удалось найти контейнер для микротика ? Если да, то киньте пожалуйста ссылку.
> 
> Дак текущий проект есть https://hub.docker.com/r/tazihad/byedpi Всё отлично работает.

Да, все верно. Я попросил разработчика там добавить образ для arm архитектуре и после этого удалось поднять на микроте

**Comment by greenvorbisfan** [comment]
Не могли бы вы разжевать поподробнее способ установки — точнее, настройки контейнера? Устанавливается, даже запускается, но при этом в логах пусто, youtube, соответственно, не работает. Подозреваю, что нужно настроить VETH, но не знаю, как именно. Заранее спасибо.

**Comment by 1ns0mn1a-god** [comment]
> Не могли бы вы разжевать поподробнее способ установки — точнее, настройки контейнера? Устанавливается, даже запускается, но при этом в логах пусто, youtube, соответственно, не работает. Подозреваю, что нужно настроить VETH, но не знаю, как именно. Заранее спасибо.

1. Создаём бридж, вешаем на него адрессацию через IP-Addresses;
2. Создаем Veth и добавляем его в бридж, прописываем в General IP и Gateway;
3. Добавляем докер в контейнер, стартуем. Проверяем пинги по адресу, корторый повесили на интерфейс;
4. Профит.

P.S. 
Я использовал следующую строку для запуска:
--hosts list.txt --disorder 1 --fake 0 --ttl 1 -A torst --tlsrec 1+s --auto=none
Файл list.txt необходимо запихать внутрь root dir, указанной в настройках контейнера (лучше по ssh).

**Comment by gospodenkods** [comment]
> > Не могли бы вы разжевать поподробнее способ установки — точнее, настройки контейнера? Устанавливается, даже запускается, но при этом в логах пусто, youtube, соответственно, не работает. Подозреваю, что нужно настроить VETH, но не знаю, как именно. Заранее спасибо.
> 
> 1. Создаём бридж, вешаем на него адрессацию через IP-Addresses;
> 2. Создаем Veth и добавляем его в бридж, прописываем в General IP и Gateway;
> 3. Добавляем докер в контейнер, стартуем. Проверяем пинги по адресу, корторый повесили на интерфейс;
> 4. Профит.
> 
> P.S. Я использовал следующую строку для запуска: --hosts list.txt --disorder 1 --fake 0 --ttl 1 -A torst --tlsrec 1+s --auto=none Файл list.txt необходимо запихать внутрь root dir, указанной в настройках контейнера (лучше по ssh).

А для  особо одареных  можете  объяснить , ну если  конечно есть такая возможность.  
Ну к примеру про  строку запуска  и содержание  вайла list.txt

**Comment by greenvorbisfan** [comment]
> P.S. Я использовал следующую строку для запуска: --hosts list.txt --disorder 1 --fake 0 --ttl 1 -A torst --tlsrec 1+s --auto=none Файл list.txt необходимо запихать внутрь root dir, указанной в настройках контейнера (лучше по ssh).

Благодарствую. Будем попробовать.

**Comment by 1ns0mn1a-god** [comment]
> А для особо одареных можете объяснить , ну если конечно есть такая возможность.
> Ну к примеру про строку запуска и содержание вайла list.txt

Всё что прописано будет в файле - обрабатывается контейнером, остальное игнорится.
Содержимое у меня:
youtubei.googleapis.com
googlevideo.com

**Comment by gospodenkods** [comment]
> > А для особо одареных можете объяснить , ну если конечно есть такая возможность.
> > Ну к примеру про строку запуска и содержание вайла list.txt
> 
> Всё что прописано будет в файле - обрабатывается контейнером, остальное игнорится. Содержимое у меня: youtubei.googleapis.com googlevideo.com

Да это я понимаю , собственно вопрос в следующем . 
В CMD Запуска  контенера указана ваша  строка. 
read/parse: No such file or directory  соотвественно  он н еможет найти файл в root dir ,  а root dir это container store . В него файл  не засунуть . Вот  сижу  туплю .

**Comment by 1ns0mn1a-god** [comment]
> Да это я понимаю , собственно вопрос в следующем .
> В CMD Запуска контенера указана ваша строка.
> read/parse: No such file or directory соотвественно он н еможет найти файл в root dir , а root dir это container store . В него файл не засунуть . Вот сижу туплю .

Подключаемся по SSH к роутеру, Вводим команду /container/print, нам показывает все контейнеры. Смотрим под каким номером он у нас стоит (обычно нумерация с 0), запомнили. Далее вводим /container/shell и нажимаем enter, нам предлагает ввести номер контейнера, вводим номер из выше запомненного, попадаем в сам контейнер. Далее прямо в корне создаём файл через редактор vi и вписываем в него адреса, сохраняем и запускаем контейнер. Всё должно работать.

**Comment by gospodenkods** [comment]
> > Да это я понимаю , собственно вопрос в следующем .
> > В CMD Запуска контенера указана ваша строка.
> > read/parse: No such file or directory соотвественно он н еможет найти файл в root dir , а root dir это container store . В него файл не засунуть . Вот сижу туплю .
> 
> Подключаемся по SSH к роутеру, Вводим команду /container/print, нам показывает все контейнеры. Смотрим под каким номером он у нас стоит (обычно нумерация с 0), запомнили. Далее вводим /container/shell и нажимаем enter, нам предлагает ввести номер контейнера, вводим номер из выше запомненного, попадаем в сам контейнер. Далее прямо в корне создаём файл через редактор vi и вписываем в него адреса, сохраняем и запускаем контейнер. Всё должно работать.

А вы  мозг !
Правла я в shell напрямую из терминала winbox зашел . Не суть .  Запустился  контейнер , буду  дома   пропишу socks5 и поглядим как заработает . Спасибо большое за ответы .

**Comment by Direnor** [comment]
> > Подскеажите, Вам удалось найти контейнер для микротика ? Если да, то киньте пожалуйста ссылку.
> 
> Дак текущий проект есть https://hub.docker.com/r/tazihad/byedpi Всё отлично работает.

Спасибо !

**Comment by romkazor** [comment]
Это все хорошо и схема с ручным указанием прокси работает. А получилось у кого прозрачно завернуть трафик через прокси? Похожую схему я провернул с xray + контейнер с tun2socks когда трафик маркируем манглом и направляем в tun2sock а тот в свою очередь уже кидает в socks и все работает. А тут никак, получаю от курла SSL_ERROR_SYSCALL, такая же петрушка и со spoof-dpi и zapret

**Comment by wiktorbgu** [comment]
Инструкция доступна через vpn [https://habr.com/ru/articles/838452/](https://habr.com/ru/articles/838452/)
