### ISSUE TITLE
ss: invalid version: 0x43 (213) 

### ISSUE THREAD

**Issue by barl0g** [hufrea/byedpi#32]
Запускается, но не работает. После попытки соединения вылазят ошибки. Браузер через прокси данные не получает.

```
$ ./ciadpi --disorder 1 --auto=torst --tlsrec 1+s
ss: invalid version: 0x43 (213) 
ss: invalid version: 0x43 (213) 
ss: invalid version: 0x43 (213)
```

**Comment by hufrea** [comment]
#18

**Comment by barl0g** [comment]
Спасибо!

**Comment by serj-lubin** [comment]
> Запускается, но не работает. После попытки соединения вылазят ошибки. Браузер через прокси данные не получает.
> 
> ```
> $ ./ciadpi --disorder 1 --auto=torst --tlsrec 1+s
> ss: invalid version: 0x43 (213) 
> ss: invalid version: 0x43 (213) 
> ss: invalid version: 0x43 (213)
> ```
Убери в насйтроках браузера чтобы запросы шли по http(s) через soks_v5 всё работает.

**Comment by lufog** [comment]
Для тех кто указывает прокси в настройках Windows 11, в новом GUI. Указываете не просто IP а socks=IP, например
`socks=127.0.0.1`. Важно понимать что этот новый GUI кривой, и с каждым перезапуском настроек в поле будет добавляться `http://`, который нужно удалять, это баг гуя.

**Comment by tribals** [comment]
В вендовых настройках надо писать `socks5=127.0.0.1`, а не `socks=`, иначе будет использована версия 4 протокола SOCKS.
