### ISSUE TITLE
Q: How can i bypass only youtube?

### ISSUE THREAD

**Issue by rscx-r1** [hufrea/byedpi#33]
Linux Mint

**Comment by hufrea** [comment]
Тут есть раздел Discussions для вопросов.
`--hosts :googlevideo.com --disorder 1`

**Comment by edvejak** [comment]
Where to write this code: '--hosts :googlevideo.com --disorder 1'

**Comment by vgglv** [comment]
> Where to write this code: '--hosts :googlevideo.com --disorder 1'?

when calling binary you pass that as argument

**Comment by edvejak** [comment]
Ok. What is better: start proxy 'ciadpi-x86_64 -i 127.0.0.1 -p 10801 -d 1 &'  or this command 'ciadpi-x86_64 --hosts :googlevideo.com --disorder 1'?

**Comment by z18d7** [comment]
You need to pass all the necessary parameters in one call

If you execute
`ciadpi-x86_64 --hosts :googlevideo.com --disorder 1`
then you'll need to use the default port 1080

If you want 10801 port then start your proxy like this
`ciadpi-x86_64 -i 127.0.0.1 -p 10801 --hosts :googlevideo.com --disorder 1`

**Comment by lufog** [comment]
@edvejak what works is better.
| Long key | Short key | Description | Default value (if not set) |
|----------------------------|----------------|-----------------------------------------|---------------------------------|
| --ip <ip>                   | -i \<ip\>       | IP that the proxy is listening to | 0.0.0.0 (all interfaces) |
| --port \<num\>         | -p \<num\>  | Port that the proxy listens to | 1080 |
| --disorder \<n[+s]\> | -d \<n[+s]\> | Splits the request at the specified offset, sending the pieces in reverse order. |  |
| --hosts \<file\|:string\> | -H \<file\|:string\> | Limit the scope of the parameters to a list of domains. Domains must be separated by a newline or a space. |  |

So both your commands are essentially the same (both use disorder). It's just that the first one explicitly specifies the IP and port. And the second one is scoped to a single domain `googlevideo.com`.
