### ISSUE TITLE
Не срабатывает правило по --host list.txt для доменов ютуба

### ISSUE THREAD

**Issue by sanek184** [hufrea/byedpi#39]
Здравствуйте. Прописываю --hosts russia-youtube.txt -s 2 --auto=none, в котором такие домены: 
youtube.com youtu.be googlevideo.com ytimg.com
И byedpi никак не реагирует на домены что в нем и ютуб шейпится. Если например взять другие домены, то правило срабатывает. И **если просто -s 2 на все использовать без list.txt - то ютуб перестает шейпится**

UPD: Вот так --hosts :googlevideo.com -s 2 - тоже не срабатывает.

**Comment by YadMM** [comment]
Попробуйте так;
--hosts russia-youtube.txt --fake -1  --mod-http=h,d --tlsrec 1+s

**Comment by sanek184** [comment]
> Попробуйте так; --hosts russia-youtube.txt --fake -1 --mod-http=h,d --tlsrec 1+s

Попробовал. Не работает также. Дело не в самих правилах фрагментации, если убрать его ютуб станет нормально воспроизводиться, но нужно ограничить в пределах этих доменов

**Comment by hufrea** [comment]
Здравствуйте. Запустите программу с параметром `--debug 1` и посмотрите, появляется ли строчка "...DESYNC SPLIT" после "host: ...googlevideo.com".

**Comment by sanek184** [comment]
> Здравствуйте. Запустите программу с параметром `--debug 1` и посмотрите, появляется ли строчка "...DESYNC SPLIT" после "host: ...googlevideo.com".

![image](https://github.com/user-attachments/assets/3936f0d4-1b76-422a-b27f-3894d9957c77)

**Comment by hufrea** [comment]
А вы какую версию используете? v0.12 же?

**Comment by sanek184** [comment]
> А вы какую версию используете? v0.12 же?

Да. Вот буквально вчера подсел на ваше приложение. Для меня через socks5 и такой функционал просто идеален.

**Comment by hufrea** [comment]
Можете скинуть файл russia-youtube.txt?

**Comment by sanek184** [comment]
> Можете скинуть файл russia-youtube.txt?
[russia-youtube.txt](https://github.com/user-attachments/files/16510647/russia-youtube.txt)

**Comment by hufrea** [comment]
Странно.
Проверьте все же версию бинарника с помощью `--version`, мало ли.
Какая ОС? Сами собирали? Если да, то чем и с какими флагами?

**Comment by sanek184** [comment]
> Странно. Проверьте все же версию бинарника с помощью `--version`, мало ли. Какая ОС? Сами собирали? Если да, то чем и с какими флагами?

![image](https://github.com/user-attachments/assets/014b3fa0-360c-4460-9598-3d48e6214362)
С гитхаба уже скомпилированную

**Comment by lufog** [comment]
Так это `0.10.2` а не `0.12.0`.

**Comment by hufrea** [comment]
У вас там 10.2, там еще поддомены не поддерживались.
Вот отсюда качаете: https://github.com/hufrea/byedpi/releases/tag/v0.12

**Comment by sanek184** [comment]
> У вас там 10.2, там еще поддомены не поддерживались. Вот отсюда качаете: https://github.com/hufrea/byedpi/releases/tag/v0.12

Е-мае) Я был точно уверен что версия 0.12.... Извиняюсь, сейчас гляну с ней.

**Comment by sanek184** [comment]
> У вас там 10.2, там еще поддомены не поддерживались. Вот отсюда качаете: https://github.com/hufrea/byedpi/releases/tag/v0.12

Еще раз извиняюсь, в 0.12 работает, понять не могу как я так промахнулся, качал с гитхаба и точно видел 0.12 релиз

**Comment by 6apakyda** [comment]
У меня тоже как-то странно ведёт себя команда, если добавить файл исключения. 
Если запускаю с командой:
--disorder 1 --fake 0 --ttl 1 -A torst --tlsrec 1+s --debug 1
Работает всё, включая инстаграмы, рутрекеры, только на телевизоре при запуске ютуба, сервый экран.
Если запускаю с командой:
--hosts list.txt --disorder 1 --fake 0 --ttl 1 -A none --debug 1
Перестают открываться сайты и выдаёт ошибку: dns_probe_started

Версия 0.12, буквально минут 15 назад обновился через докер хаб.

**Comment by sanek184** [comment]
> У меня тоже как-то странно ведёт себя команда, если добавить файл исключения. Если запускаю с командой: --disorder 1 --fake 0 --ttl 1 -A torst --tlsrec 1+s --debug 1 Работает всё, включая инстаграмы, рутрекеры, только на телевизоре при запуске ютуба, сервый экран. Если запускаю с командой: --hosts list.txt --disorder 1 --fake 0 --ttl 1 -A none --debug 1 Перестают открываться сайты и выдаёт ошибку: dns_probe_started
> 
> Версия 0.12, буквально минут 15 назад обновился через докер хаб.
Перестает открываться ютуб вообще с -A none, вот так у себя замеил для пробы --auto=none. Похоже не правильный синтаксис
S:\-ADMIN-\_Se7en_\WireGuard\ByeDPI>ciadpi.exe -i 127.0.0.1 -p 10800 --hosts russia-blacklist.txt -o 2 -A none --hosts russia-youtube.txt -s 2 -A none

**Comment by 6apakyda** [comment]
Если вместо -A none указать --auto=none выдаёт ошибку
Я запускаю контейнер на synology.
![Screenshot_19](https://github.com/user-attachments/assets/e323070a-33a9-4faf-83ba-d4a59049b27d)

**Comment by sanek184** [comment]
> Для параметров с опциональным аргументом значение нужно писать через знак равенства `-A none` -> `--auto=none` А еще у вас есть параметр `--fake 0` - она не имеет смысла, уберите ее.

Пользуясь случаем, а как прописать все условия, просто через запятую ?

**Comment by hufrea** [comment]
Условия для auto?
`--auto=torst,redirect`
Но с none так не выйдет, он должен быть один.

**Comment by sanek184** [comment]
> Условия для auto? `--auto=torst,redirect` Но с none так не выйдет, он должен быть один.
Проверил сейчас:
1. Отрабатывает с A none
 ciadpi.exe -i 127.0.0.1 -p 10800 --hosts russia-youtube.txt -s 2 -A none
2. А вот так второй txt что с ютубом нет
-i 127.0.0.1 -p 10800 --hosts russia-blacklist.txt -o 2 -A none --hosts russia-youtube.txt -s 2 -A none
С --auto=none все нормально.

**Comment by 6apakyda** [comment]
> Для параметров с опциональным аргументом значение нужно писать через знак равенства `-A none` -> `--auto=none` А еще у вас есть параметр `--fake 0` - она не имеет смысла, уберите ее.
Как у уже писал, система не даёт поставить эту команду, пишет не верный формат выполняемый команды.

**Comment by sanek184** [comment]
Некоторые сайты с 1 txt при -A none ломаются. У меня явно оно не отрабатывается.

**Comment by 6apakyda** [comment]
> Некоторые сайты с первого txt при -A none ломаются. Ютуб со второго txt вообще пишет ERR_FAILED. У меня явно оно не отрабатывается. C --auto=none все отлично, что-то с аргументом -A none действительно не так

Чуть выше писали, что так и не будет работать:

> Для параметров с опциональным аргументом значение нужно писать через знак равенства
-A none -> --auto=none

**Comment by 6apakyda** [comment]
> Если вместо -A none указать --auto=none выдаёт ошибку Я запускаю контейнер на synology. ![Screenshot_19](https://private-user-images.githubusercontent.com/136457611/355561769-e323070a-33a9-4faf-83ba-d4a59049b27d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NzA4MzYsIm5iZiI6MTcyMjk3MDUzNiwicGF0aCI6Ii8xMzY0NTc2MTEvMzU1NTYxNzY5LWUzMjMwNzBhLTMzYTktNGZhZi04M2JhLWQ0YTU5MDQ5YjI3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxODU1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDE1NzUxMmY0M2EwNWIxMzEwN2QzNDZlOTg2ZTg3NTk1NTU3ZTgzNGNjZjZjOTllM2FiNzI3M2I4OTc5YWJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yCWyYab_bjHytUTbqngL1b0ix36p8KxS0XZSuI6AI-s)

Подскажите, а вот по поводу этой ошибки при сборки контейнера, стоит ждать какого-то обновления?
