### ISSUE TITLE
Лицензия byedpi 

### ISSUE THREAD

**Issue by ProMix0** [hufrea/byedpi#43]
Хочу добавить пакет в Gentoo, да и вообще интересно - какая у проекта лицензия?

Если это не первостепенный вопрос, можно ли указать какую-нибудь?

**Comment by hufrea** [comment]
> можно ли указать какую-нибудь?

Да

**Comment by raspopov** [comment]
Может быть MIT? Добавьте, пожалуйста, файл LICENSE в репу.

**Comment by ProMix0** [comment]
> Да

В смысле можете ли вы? Я-то, ясное дело, любую хрень написать могу 

Так что я присоединюсь к просьбе @raspopov

**Comment by ProMix0** [comment]
Благодарю
