### ISSUE TITLE
При запуске вешает контейнер в proxmox 

### ISSUE THREAD

**Issue by dumbodumbos** [hufrea/byedpi#48]
Добрый. Контейнер создан на базе Ubuntu 24.04 LTS (GNU/Linux 6.8.12-1-pve x86_64). Promox на базе NUC. Архив положен в /opt/byedpi - распакован. 

-rw-r--r-- 1 root root  70915 Jul 29 20:34 byedpi-12-x86_64.tar.gz
-rwxr-xr-x 1 root root 133776 Jul 29 20:24 ciadpi-x86_64

<img width="917" alt="Снимок экрана 2024-08-08 в 15 54 04" src="https://github.com/user-attachments/assets/618a8f46-9801-44b9-89d8-96f85403c9ae">

При запуске с  ./ciadpi-x86_64 --disorder 1 --fake 0 --ttl 1 -A torst --tlsrec 1+s --debug 1  - да в принципе с любыми ключами вешает контейнер. 

Что я делаю не так ?

**Comment by hufrea** [comment]
> вешает контейнер.

Как это проявляется? Программа игнорирует ctrl+c?  `top` показывает какую либо нагрузку? Какая реакция на попытку поключения (есть что-либо в логах)?

**Comment by dumbodumbos** [comment]
> > вешает контейнер.
> 
> Как это проявляется? Программа игнорирует ctrl+c? `top` показывает какую либо нагрузку? Какая реакция на попытку поключения (есть что-либо в логах)?

В топе ни какой нагрузки нет 
<img width="485" alt="Снимок экрана 2024-08-10 в 13 57 08" src="https://github.com/user-attachments/assets/1d2bfb33-e6d2-4c8a-8f94-d93864956b91">

ctrl+c - снимает задачу. 

Если задачу не снять переподключиться к контенеру нельзя

**Comment by ProMix0** [comment]
Ну я даже не знаю, а чего вы ожидаете, запуская программу не в фоне и никак её не используя?

**Comment by dumbodumbos** [comment]
> Ну я даже не знаю, а чего вы ожидаете, запуская программу не в фоне и никак её не используя?

Поясните мне не умному. Как запустить в фоне ?

**Comment by ProMix0** [comment]
В идеале через systemd unit

В крайнем случае, или для быстрого теста, добавить в конец команды амперсанд:

```
 ./ciadpi-x86_64 --disorder 1 --fake 0 --ttl 1 -A torst --tlsrec 1+s --debug 1 &
```

**Comment by dumbodumbos** [comment]
> В идеале через systemd unit
> 
> В крайнем случае, или для быстрого теста, добавить в конец команды амперсанд:
> 
> ```
>  ./ciadpi-x86_64 --disorder 1 --fake 0 --ttl 1 -A torst --tlsrec 1+s --debug 1 &
> ```

Так запустилось. Спасибо.

**Comment by dumbodumbos** [comment]
./ciadpi-x86_64 --disorder 1 --fake 0 --ttl 1 -A torst --tlsrec 1+s --debug 1 & - вот так все заработало
