### ISSUE TITLE
 В тг

### ISSUE THREAD

**Issue by MistFenix** [hufrea/byedpi#6]
Здравствуйте, спасибо за инструмент, можно вас в ТГ добавить? Пожалуйста

**Comment by hufrea** [comment]
Вы можете связаться со мной на форуме: https://ntc.party/u/hufrea

**Comment by MistFenix** [comment]
Хорошо, спасибо большое за быстрый ответ

**Comment by MistFenix** [comment]
Извиняюсь что беспокою вас.

Хотел бы поговорить про то где что изучать чтобы понять работы Dpi систему в основном, конечно хочется изучать C для этого но само изучение C не дает возможности понять вашу работу а я восхищаюсь как вы создаёте профессиональный инструмент. За информацию где что изучать буду благодарен и конечно же оплатить готов. Надеюсь поможете, а если откажете то понимаю вас, спасибо большое за ранее.

**Comment by hufrea** [comment]
Я оставлял в readme несколько ссылок на документы/статьи, описывающие принцип работы подобных программ. Если вам они непонятны, то следует сначала изучить работу сети, акцентируясь на TCP/IP. На той же википедии кратко (но сухо) расписаны суть и принцип работы этих протоколов. Можно прочитать небольшую книжку или цикл статей о компьютерных сетях. Их немало, что-то конкретное посоветовать не могу, тут самому искать, что легче воспринимается.

**Comment by MistFenix** [comment]
Хорошо, спасибо большое
