### ISSUE TITLE
Что я делаю не правильно? Настроил! Всё работает 👍

### ISSUE THREAD

**Issue by lp85d** [hufrea/byedpi#60]
[https://pastein.ru/t/ZhX](https://pastein.ru/t/ZhX)
wget https://github.com/hufrea/byedpi/releases/download/v0.12/byedpi-12-aarch64.tar.gz
tar -tzf byedpi-12-aarch64.tar.gz
tar -xzf byedpi-12-aarch64.tar.gz
./ciadpi-aarch64 --ip 0.0.0.0 --port 1080 --tls-sni "www.youtube.com" --debug 1 > output.log 2>&1
cat output.log
sni: www.youtube.com
exit
![image](https://github.com/user-attachments/assets/f572e0ff-4808-41b8-b054-bb37392b4d32)

**Comment by lp85d** [comment]
Запускаю команды и сайт всё равно не открывается
Пробовал открыть localhost:port из конфигурации и вот что выводит
[https://pastein.ru/t/hhX](https://pastein.ru/t/hhX)

**Comment by lp85d** [comment]
![image](https://github.com/user-attachments/assets/17445ab3-2b7b-4d0f-8cb3-e7d79c13bc93)
![image](https://github.com/user-attachments/assets/e2ca4908-af89-4ef0-9f2c-7028b28c93c0)

**Comment by hufrea** [comment]
Вы указали HTTPS прокси, а нужно SOCKS, порт 1080.

**Comment by lp85d** [comment]
Я правильно запускаю?
./ciadpi-aarch64 --ip 0.0.0.0 --port 1080 --tls-sni "www.youtube.com" --disorder 1 --auto=torst --tlsrec 1+s --debug 1
Не получается всё равно https://pastein.ru/t/AhX
![image](https://github.com/user-attachments/assets/91375499-5785-4b2d-a82d-20221948ff21)

**Comment by lp85d** [comment]
Урааа!!! Всё работает!!!
![image](https://github.com/user-attachments/assets/15e79b28-9336-4bcb-abed-a6e5360e3f71)
