### ISSUE TITLE
readme.txt -> README.md

### ISSUE THREAD

**Issue by vladiscripts** [hufrea/byedpi#77]
Описание приложения в [readme.txt](https://github.com/hufrea/byedpi/blob/main/readme.txt) сложновато читать, поскольку нет оформления разметкой [MD markdown](https://docs.github.com/ru/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax). Хотя в тексте коды этой разметки присутствуют - `###` в заголовках разделов.
Чтобы разметка работала надо переименовать `readme.txt` в `README.md`.

**Comment by hufrea** [comment]
Дела в том, что раздел "Описание аргументов" занимал большую часть текста, а он должен быть написан моноширинным шрифтом. В итоге в MD была лишь пара предложений, а остальная часть являлась "кодом", что смотрелось плохо.
