### ISSUE TITLE
Systemwide tunneling possible?

### ISSUE THREAD

**Issue by HakaishinShwet** [hufrea/byedpi#89]
like is it possible to tunnel every traffic of our system through this programs dpi tunnel?

**Comment by lufog** [comment]
If you mean launching a program, and it will automatically redirect all traffic through itself, like [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI), then no. This is a local proxy that must be explicitly specified in the system (or browser) settings. Moreover, even if you specify a proxy in the system settings, this does not guarantee that all programs will use it. For example, Windows Store and UWP applications will not use a local proxy ([without hacks](https://github.com/krlvm/PowerTunnel/issues/102#issuecomment-1244411866)). But regular applications in most cases work without problems through a proxy.

**Comment by zimbabwe303** [comment]
[redsocks](https://github.com/darkk/redsocks) or [tsocks](https://github.com/zouguangxian/tsocks) will do the job. Both are available from the official repositories of many Linux distros.
