### ISSUE TITLE
Добавить игнор-лист?

### ISSUE THREAD

**Issue by semenInRussia** [hufrea/byedpi#93]
Что насчёт добавить какую-то опцию `--ignore`, обьявляющую список доменов, которых byedpi косаться не должен?

**Comment by lufog** [comment]
Рекомендую почитать [ReadMe](https://github.com/hufrea/byedpi/blob/main/README.md). Это уже можно делать:
```
--hosts list.txt --disorder 3 --auto=none
```
Применять запутывание только для доменов из list.txt

```
--hosts list.txt --auto=none --disorder 3
```
Не применять запутывание для доменов из list.txt
