### ISSUE TITLE
File "list.txt" on android

### ISSUE THREAD

**Issue by pipipupu-ui** [hufrea/byedpi#94]
Where should I create a white or black list file of domains on android to simply specify its name? Or how to specify the path to a file located not next to the program?

**Comment by zimbabwe303** [comment]
Put it in anywhere you like and give the full system path to the --hosts parameter. For example for `Internal Storage/Documents/hosts_whitelist.txt` it will be `--hosts /storage/emulated/0/Documents/hosts_whitelist.txt`

**Comment by pipipupu-ui** [comment]
> Поместите его в любое место, которое вам нравится, и укажите полный системный путь к параметру --hosts. Например, для `Internal Storage/Documents/list.txt`него это будет`--hosts /storage/emulated/0/Documents/list.txt`

*Faild to start proxy*

**Comment by zimbabwe303** [comment]
Создал тикет: https://github.com/dovecoteescapee/ByeDPIAndroid/issues/97
