### ISSUE TITLE
Fix infinite proxy loop

### ISSUE THREAD

**Issue by f0xeri** [hufrea/byedpi#95]
При некоторых условиях (например, когда запущен тунель, подключающийся к прокси) может получиться бесконечный цикл подключений.
Легко воспроизвести даже на win/linux. Запускаем byedpi, в nekoray (или любой программе с аналогичным функционалом) подключаемся к нашему socks5 в режиме tun или системного прокси, получаем бесконечный коннект.

Описание проблемы у другого socks5 сервера - https://github.com/tinyproxy/tinyproxy/issues/199
Пример их фикса - https://github.com/tinyproxy/tinyproxy/pull/218/commits/b6cb68734da66843b07ebae9669c5e79e20bae20

**Comment by hufrea** [comment]
> например, когда запущен тунель, подключающийся к прокси

Если туннелируются соединения от прокси, то защита от цикла не поможет. Цикл в таком случае не является некорректным поведением и вполне ожидаем. Нужно исключить сервер из туннеля, на Linux это делается с помощью iptables и запуском бинарника от другого пользователя.
